# Generated by Django 3.0.2 on 2020-01-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubeuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='IDimg/'),
        ),
        migrations.AlterField(
            model_name='cubeuser',
            name='address',
            field=models.CharField(default='未知', max_length=100, verbose_name='邮寄地址'),
        ),
        migrations.AlterField(
            model_name='cubeuser',
            name='emergencyname',
            field=models.CharField(default='未知', max_length=10, verbose_name='紧急联络人姓名'),
        ),
        migrations.AlterField(
            model_name='cubeuser',
            name='emergencyphone',
            field=models.CharField(default='未知', max_length=20, verbose_name='紧急联络人电话'),
        ),
    ]
