# Generated by Django 3.0.2 on 2020-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeuser', '0002_auto_20200118_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubeuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='IDimg/', verbose_name='图片'),
        ),
    ]
